name: secret-detection for java gradle

on:
    workflow_call:
        
jobs:
 secret-detection: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: detect secrets
        run: |
            pip install detect-secrets
            scan_result=$(detect-secrets scan)
            if echo "$scan_result" | grep -q '"hashed_secret":'; then
            echo "Secrets were found during the scan:"
            echo "$scan_result"
            #exit 1
            else
            echo "No secrets were found."
            fi
            echo "Current Directory (PWD): $PWD" 
